name: Build Micropython
on:
  pull_request:
  workflow_dispatch:
  push:
    branches: main
jobs:
  Build-Firmware:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential python3-pip libusb-1.0-0-dev cmake
          sudo python3 -m pip install pillow
      - name: Check out driver code
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Check out ESP IDF
        uses: actions/checkout@v2
        with:
          repository: espressif/esp-idf
          ref: v4.4
          path: esp-idf
          submodules: true
      - name: Install SDK
        run: |
          cd esp-idf
          ./install.sh
          source export.sh
      - name: Patch submodule dependencies
        run: |
          ./scripts/firstTime.sh
      - name: Build cross compiler
        run: |
          source esp-idf/export.sh
          cd micropython
          make -C mpy-cross
      - name: Link board definition
        run: |
          source esp-idf/export.sh
          cd micropython/ports/esp32/boards
          ln -sfn ../../../../tildamk6 ./tildamk6
      - name: Build firmware
        run: |
          source esp-idf/export.sh
          ln -sfn $GITHUB_WORKSPACE/tildamk6 micropython/ports/esp32/boards/tildamk6
          cd micropython/ports/esp32
          make submodules BOARD=tildamk6 USER_C_MODULES=$GITHUB_WORKSPACE/drivers/micropython.cmake IOT_SOLUTION_PATH=$GITHUB_WORKSPACE/esp-iot-solution TARGET=esp32s3
          make BOARD=tildamk6 USER_C_MODULES=$GITHUB_WORKSPACE/drivers/micropython.cmake $@ IOT_SOLUTION_PATH=$GITHUB_WORKSPACE/esp-iot-solution TARGET=esp32s3
      - name: Archive firmware
        uses: actions/upload-artifact@v3
        with:
          name: firmware
          path: |
            micropython/ports/esp32/build-tildamk6/micropython.bin
            micropython/ports/esp32/build-tildamk6/bootloader/bootloader.bin
            micropython/ports/esp32/build-tildamk6/partition_table/partition-table.bin
